name: Maven CI/CD

on:
 push:
    branches: [ TIS-646 ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 ##action to give our job access to code in our repo
    - name: Set up JDK 14
      uses: actions/setup-java@v3 ##this action sets up a java environment that our job can run in
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
