name: Maven CI/CD

on:
 push:
    branches: [ TIS-646 ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v3 ##action to give our job access to code in our repo

    - name: Cache local mvn repo
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: v1-dependencies-{{ hashFiles('**/pom.xml') }}
        restore-keys: |
          v1-dependencies-
    - run: mvn dependency:go-offline
        

    - name: PWD
      run: pwd

    - name: LS
      run: ls
      
    - name: Set up JDK 8
      uses: actions/setup-java@v1 ##this action sets up a java environment that our job can run in
      with:
        java-version: 8
   

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
