name: Maven CI/CD

on:
 push:
    branches: [ TIS-646 ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v3 ##action to give our job access to code in our repo

    - name: Cache local mvn repo
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: v1-dependencies-{{ hashFiles('**/pom.xml') }}
        restore-keys: |
          v1-dependencies-
    - run: mvn dependency:go-offline
        

    - name: setting env
      run: echo "testTempGpg=$(echo $tempGpgValue | base64 -d)" >> $GITHUB_OUTPUT
      id: setKey
      
    - name: Configuring GPG key 
      run: |
        echo $GPG_SIGNING_KEY | base64 --decode | gpg --batch --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.SECRING_GPG_ASC_BASE64 }}

      
    - name: Set up JDK 8
      uses: actions/setup-java@v1 ##this action sets up a java environment that our job can run in
      with:
        java-version: 8
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: SERVER_OSSRH_USERNAME # env variable for username in deploy
        server-password: SERVER_OSSRH_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ steps.setKey.outputs.testTempGpg }} #${{ secrets.SECRING_GPG_ASC_BASE64 }}  Value of the GPG private key to import
        gpg-passphrase:  GPG_PASSPHRASE  # env variable for GPG private key passphrase
        #overwrite-settings: false

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Apache Maven Central
      run: mvn clean deploy -DdeployAtEnd=true -DperformRelease=true -DskipTests -Dspotbugs.skip=true
      #run: mvn -s .github/workflows/maven-release-setting.xml clean deploy -DdeployAtEnd=true -DperformRelease=true -DskipTests -Dspotbugs.skip=true
      env:
        SERVER_OSSRH_USERNAME: ${{ secrets.SERVER_OSSRH_USERNAME }}
        SERVER_OSSRH_PASSWORD: ${{ secrets.SERVER_OSSRH_PASSWORD }}
        #SECRING_GPG_ASC_BASE64: ${{ secrets.SECRING_GPG_ASC_BASE64 }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
